// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiwarwbslhipgbhcthjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pd2Fyd2JzbGhpcGdiaGN0aGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTkwMDAsImV4cCI6MjA2MTIzNTAwMH0.EJaTo5fGCmfFB7bM5g2x2X4I4GxckHNyDDo0hPb5kvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);